version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres-sis-esco
    environment:
      - POSTGRES_DB=escola_db
      - POSTGRES_USER=escola_user
      - POSTGRES_PASSWORD=escola_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_exporter:
    image: quay.io/prometheus/postgres-exporter:v0.10.0
    container_name: postgres_exporter
    environment:
      # DATA_SOURCE_NAME: conecta com o PostgreSQL usando o nome do serviço "postgres"
      - DATA_SOURCE_NAME=postgres://escola_user:escola_pass@postgres:5432/escola_db?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus-sis-esco
    volumes:
      - ./Observabilidade/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-sis-esco
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:


###> Explicação: > - Este arquivo provisiona os containers para PostgreSQL, postgres_exporter, Prometheus e Grafana. > - O arquivo de configuração do Prometheus será montado a partir da pasta Observabilidade/prometheus/.