services:
  postgres:
    image: postgres:13
    container_name: postgres-sis-esco
    environment:
      - POSTGRES_DB=escola_db
      - POSTGRES_USER=escola_user
      - POSTGRES_PASSWORD=escola_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgres://escola_user:escola_pass@postgres:5432/escola_db?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  sis-esco-api:
    build:
      context: ./app
    container_name: sis-esco-api
    ports:
      - "5000:5000"
    volumes:
      - ./app/school.db:/app/school.db     # agora o arquivo existe!
    restart: unless-stopped
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus-sis-esco
    volumes:
      - ./Observabilidade/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter
      - sis-esco-api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-sis-esco
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:
