# Usa imagem leve e oficial do Python
FROM python:3.10-slim

# Evita prompts e garante operações não-interativas
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Atualiza o sistema e instala dependências básicas
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc libpq-dev curl netcat-openbsd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# Define o diretório de trabalho
WORKDIR /app

# Copia e instala dependências primeiro (melhora cache do Docker)
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copia todo o restante do código
COPY . .

# Expõe a porta 5000
EXPOSE 5000

# Define a variável de ambiente padrão (pode ser sobrescrita via docker-compose)
ENV FLASK_APP=app
ENV FLASK_RUN_HOST=0.0.0.0

# Comando para rodar o app
CMD ["flask", "run"]
