global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sis-esco-api'
    static_configs:
      - targets: ['sis-esco-api:5000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
